FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0


RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/tinluu-nj/facefusion.git

WORKDIR /facefusion
RUN python install.py --onnxruntime default --skip-conda
