FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV GRADIO_SERVER_NAME=0.0.0.0

RUN apt-get update
RUN apt-get install python3.10 -y
RUN apt-get install python-is-python3 -y
RUN apt-get install pip -y
RUN apt-get install git -y
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y
RUN apt-get install jq -y

RUN git clone https://github.com/tinluu-nj/facefusion.git

WORKDIR /facefusion
RUN mkdir -p .assets .caches .jobs src.d
RUN python install.py --onnxruntime cuda --skip-conda

